<a href="https://colab.research.google.com/github/antkeser/KursAI/blob/main/2_Biblioteka_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python --version

Python 3.11.11


In [3]:
!pip freeze  | grep numpy

numpy==1.26.4


In [10]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(array)
print(f"Kształt tablicy: {np.shape(array)}")

array2x6 = array.reshape(2, 6)
print("array 2x6")
print(array2x6)
print(f"array 2x6 - kształt {np.shape(array2x6)}")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Kształt tablicy: (12,)
array 2x6
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
array 2x6 - kształt (2, 6)


In [11]:
array3x4 = array.reshape(3, 4)
print("array 3x4")
print(array3x4)
print(f"array 3x4 - kształt {np.shape(array3x4)}")

array 3x4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
array 3x4 - kształt (3, 4)


In [14]:
array2x2x3 = array.reshape(2, 2, 3)
print("array 2x2x3")
print(array2x2x3)

array 2x2x3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [24]:
unsorted2D = np.array([[7,2,9],
                       [4,8,1],
                       [5,6,3]])
print(unsorted2D)
sorted2D_axis0 = np.sort(unsorted2D, axis=0)
print(sorted2D_axis0)
sorted2D_axis1 = np.sort(unsorted2D, axis=1)
print(sorted2D_axis1)

[[7 2 9]
 [4 8 1]
 [5 6 3]]
[[4 2 1]
 [5 6 3]
 [7 8 9]]
[[2 7 9]
 [1 4 8]
 [3 5 6]]
