<a href="https://colab.research.google.com/github/antkeser/KursAI/blob/main/2_Biblioteka_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!python --version

Python 3.11.11


In [9]:
!pip freeze  | grep numpy

numpy==1.26.4


In [8]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(array)
print(f"Kształt tablicy: {np.shape(array)}")

array2x6 = array.reshape(2, 6)
print("array 2x6")
print(array2x6)
print(f"array 2x6 - kształt {np.shape(array2x6)}")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Kształt tablicy: (12,)
array 2x6
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
array 2x6 - kształt (2, 6)


In [ ]:
array3x4 = array.reshape(3, 4)
print("array 3x4")
print(array3x4)
print(f"array 3x4 - kształt {np.shape(array3x4)}")

array 3x4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
array 3x4 - kształt (3, 4)


In [ ]:
array2x2x3 = array.reshape(2, 2, 3)
print("array 2x2x3")
print(array2x2x3)

array 2x2x3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
unsorted2D = np.array([[7,2,9],
                       [4,8,1],
                       [5,6,3]])
print(unsorted2D)
sorted2D_axis0 = np.sort(unsorted2D, axis=0)
print(sorted2D_axis0)
sorted2D_axis1 = np.sort(unsorted2D, axis=1)
print(sorted2D_axis1)

[[7 2 9]
 [4 8 1]
 [5 6 3]]
[[4 2 1]
 [5 6 3]
 [7 8 9]]
[[2 7 9]
 [1 4 8]
 [3 5 6]]


In [10]:
player_data = np.array([
    ("Faker", "T1", 5),
    ("TheSky", "Weibo Gaming", 1),
    ("Uzi", "Emerytowany", 0)
], dtype = [("Nick", "U30"), ("Team", "U30"), ("Worlds Title count", "i4")])

print(player_data)


print(np.sort(player_data, order= "Team"))

[('Faker', 'T1', 5) ('TheSky', 'Weibo Gaming', 1)
 ('Uzi', 'Emerytowany', 0)]
[('Uzi', 'Emerytowany', 0) ('Faker', 'T1', 5)
 ('TheSky', 'Weibo Gaming', 1)]


In [17]:
from numpy import random

for i in range(10):
    print(random.randint(1,11))

for i in range(10):
  print(random.rand()*10)

2
2
5
3
10
1
9
2
6
7
6.420712670464594
0.14809463073747975
3.152274826464586
1.7109075057695022
0.4484766159964304
7.611181342709683
9.105565567690808
2.6216016334154437
6.98471635688012
3.9980458389596585


In [18]:
lista = [1,2,3,4]

print(random.choice(lista,3))

[4 2 4]


In [20]:
array1D =  np.array([1,2,3,4,5,6,7,8,9])

print(array1D[ :5])

print(array1D[2:5])
print(array1D[3:])
print(array1D[-3:-1])

[1 2 3 4 5]
[3 4 5]
[4 5 6 7 8 9]


In [25]:
array2D = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])

print(array2D[2,1])

print(array2D[:,2:4])

for i in np.nditer(array2D):
    print(i)

12
[[ 3  4]
 [ 8  9]
 [13 14]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [35]:
array2D = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,6]
])

result = np.where(array2D == 6)
print(result)

result = np.where(array2D % 2 == 0, True, False)
print(result)

filtred = array2D[result]
print(filtred)

(array([1, 2]), array([0, 4]))
[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True  True]]
[ 2  4  6  8 10 12 14  6]
